[build]
  # IMPORTANT: In Netlify UI, set 'Base directory' to 'AuraFy_Frontend'.
  # This 'publish' then means the root of that 'Base directory'.
  publish = "." #
  command = "echo No build command" # No build command is needed for static HTML/CSS/JS

# Redirects are crucial for your HTML files which are in 'templates'
# This ensures paths like / or /quiz get mapped correctly.
# If your app navigates client-side, these also ensure direct URL access works.

# Redirect for the main landing page
[[redirects]]
  from = "/"
  to = "/templates/index.html" # Redirects the base URL to your main index.html
  status = 200

# Redirects for your other HTML pages
[[redirects]]
  from = "/quiz"
  to = "/templates/quiz.html" #
  status = 200

[[redirects]]
  from = "/user-info"
  to = "/templates/user-info.html" #
  status = 200

[[redirects]]
  from = "/result"
  to = "/templates/result.html" #
  status = 200

[[redirects]]
  from = "/exit"
  to = "/templates/exit.html" #
  status = 200
