[build]

  # It's better to let Netlify implicitly set the base from the UI's 'Base directory' for simplicity.
  publish = "templates" # <--- Remove the leading slash!
  command = "echo No build command"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200